# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcommand.proto\x12\x06turret\"8\n\x12SetPositionCommand\x12\x0f\n\x07\x61zimuth\x18\x01 \x01(\x02\x12\x11\n\televation\x18\x02 \x01(\x02\"J\n\x12SetVelocityCommand\x12\x18\n\x10\x61zimuth_velocity\x18\x01 \x01(\x02\x12\x1a\n\x12\x65levation_velocity\x18\x02 \x01(\x02\"\x14\n\x12GetPositionCommand\"\x14\n\x12GetVelocityCommand\";\n\x15SetCalibrationCommand\x12\x0f\n\x07\x61zimuth\x18\x01 \x01(\x02\x12\x11\n\televation\x18\x02 \x01(\x02\"\x0e\n\x0cResetCommand\"\xca\x02\n\x07\x43ommand\x12\x32\n\x0cset_position\x18\x01 \x01(\x0b\x32\x1a.turret.SetPositionCommandH\x00\x12\x32\n\x0cset_velocity\x18\x02 \x01(\x0b\x32\x1a.turret.SetVelocityCommandH\x00\x12\x32\n\x0cget_position\x18\x03 \x01(\x0b\x32\x1a.turret.GetPositionCommandH\x00\x12\x32\n\x0cget_velocity\x18\x04 \x01(\x0b\x32\x1a.turret.GetVelocityCommandH\x00\x12\x38\n\x0fset_calibration\x18\x05 \x01(\x0b\x32\x1d.turret.SetCalibrationCommandH\x00\x12%\n\x05reset\x18\x06 \x01(\x0b\x32\x14.turret.ResetCommandH\x00\x42\x0e\n\x0c\x63ommand_typeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'command_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SETPOSITIONCOMMAND._serialized_start=25
  _SETPOSITIONCOMMAND._serialized_end=81
  _SETVELOCITYCOMMAND._serialized_start=83
  _SETVELOCITYCOMMAND._serialized_end=157
  _GETPOSITIONCOMMAND._serialized_start=159
  _GETPOSITIONCOMMAND._serialized_end=179
  _GETVELOCITYCOMMAND._serialized_start=181
  _GETVELOCITYCOMMAND._serialized_end=201
  _SETCALIBRATIONCOMMAND._serialized_start=203
  _SETCALIBRATIONCOMMAND._serialized_end=262
  _RESETCOMMAND._serialized_start=264
  _RESETCOMMAND._serialized_end=278
  _COMMAND._serialized_start=281
  _COMMAND._serialized_end=611
# @@protoc_insertion_point(module_scope)
